CREATE TABLE IF NOT EXISTS vouchers (
	id BIGINT(255) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	voucher_code VARCHAR(255) NOT NULL,
	amount_in_percent INT(255) UNSIGNED NOT NULL,
	start_date DATETIME NOT NULL,
	end_date DATETIME NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
